### ISSUE TITLE
ControlMsrE2.efi in "interactive" mode freezes computer

### ISSUE THREAD

**Issue by mackonsti** [utopia-team/opencore-debug#1]
Hello to the developer team, many thanks for. your constant efforts!

I have tried to use your published **ControlMsrE2.efi** by adding it to EFI/OC/Tools/ folder then adding to my `config.plist`:

```
			<dict>
				<key>Arguments</key>
				<string></string>
				<key>Auxiliary</key>
				<true/>
				<key>Comment</key>
				<string>Control MSR Lock</string>
				<key>Enabled</key>
				<true/>
				<key>Name</key>
				<string>Control MSR Lock</string>
				<key>Path</key>
				<string>ControlMsrE2.efi</string>
				<key>RealPath</key>
				<false/>
				<key>TextMode</key>
				<false/>
			</dict>
```

Without "Arguments" on first run, I saw it ra in VERIFY mode and worked fine, I could press any keyboard key to return to OC's picker.

As the options are **lock** or **unlock** or **interactive**, I added **interactive** as arguments to see how it works and what it looks for in my EFI NVRAM, this way:

```
			<dict>
				<key>Arguments</key>
				<string>interactive</string>
				<key>Auxiliary</key>
				<true/>
				<key>Comment</key>
				<string>Control MSR Lock</string>
				<key>Enabled</key>
				<true/>
				<key>Name</key>
				<string>Control MSR Lock</string>
				<key>Path</key>
				<string>ControlMsrE2.efi</string>
				<key>RealPath</key>
				<false/>
				<key>TextMode</key>
				<false/>
			</dict>
```

Upon next boot, when this tool entry, it did run but then the computer froze (no keyboard input or anything at all) when it asked me to confirm something (I guess with some letter Y or N not sure).

a) Is this `config.plist` structure above correct?
b) Have you noticed freezes in **interactive** mode?
c) Is this EFI tool in some _stable_ status, to be tried out by other users? Is this a "debug" and not "release" version of the tool?
d) Does this EFI tool need OpenCore Debug version or can it run independently as I have tried?

Using OpenCore 0.6.5 on Intel NUC10i7FNH computer (Comet Lake) and a USB wired keyboard. BIOS is FN0047 from Intel.
Thank you.

P.S. In your release, your `config.plist` has twice the entry `<string>Interactive MsrE2 controller for unlocking CFG Lock</string>` that is erroneously present in **OpenControl.efi** entry.

**Comment by 1alessandro1** [comment]
Hi, thanks for the heads up, it should be fixed now.
Check the latest release, we added even more debugging tools 👍
